[package]
authors = ["Realis Network <hello@realis.network>"]
description = "node runtime primitives"
edition = "2018"
homepage = "https://realis.network/"
license = "GPL-3.0"
name = "realis-primitives"
readme = "README.md"
repository = "https://github.com/RealisNetwork/Realis.Network"
version = "0.0.1"

[dependencies]
# substrate
sp-core = { git = "https://github.com/paritytech/substrate", rev = "0bda86540d44b09da6f1ea6656f3f52d5447db81", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "0bda86540d44b09da6f1ea6656f3f52d5447db81", default-features = false }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]