version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "./target/release/realis --chain=realis --ws-port 9944  --rpc-port 9933  --validator  --rpc-methods=Unsafe  --listen-addr /ip4/0.0.0.0/tcp/30333 --name MyNode01 --unsafe-ws-external --unsafe-rpc-external --rpc-cors '*' -d ../soul/nikita"
