version: "2.2"

services:
  blockchain:
    build: 
      context: .
      dockerfile: local.Dockerfile
    ports:
      - 9944:9944
      - 9044:9044
      - 9033:9033

  nats:
    image: nats-streaming
    ports:
      - "${NATS_PORT}:4222"
    command: '--max_channels=2000'
    env_file:
      - .env
  
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # username: postgres
      POSTGRES_DB: ${DATABASE_NAME} # db name
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    # volumes:
    #   - ${HOME}/.postgres:/root/.postgres
